Models/Invite.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace JamesonBugTracker.Models
{
    public class Invite
    {
        public int Id { get; set; }
        [DisplayName("Invite Date")]
        public DateTimeOffset InviteDate { get; set; }
        
        [DisplayName("Code")]
        public Guid CompanyToken { get; set; }
        
        [DisplayName("Company")]
        public int CompanyId { get; set; }
        
        [DisplayName("Project")]
        public int ProjectId { get; set; }
        
        [DisplayName("Invite Recipient")]
        public string RecipientId { get; set; }
        
        [DisplayName("Invite Sender")]
        public string SenderId { get; set; }
        
        [DisplayName("Recipient Email")]
        public string RecipientEmail { get; set; }
        
        [DisplayName("Recipient First Name")]
        public string FirstName { get; set; }

        [DisplayName("Recipient Last Name")]
        public string LastName { get; set; }
        
        [DisplayName("Is Valid")]
        public bool IsValid { get; set; }
        
        public virtual Company Company { get; set; }
        
        public virtual Project Project { get; set; }
        
        public virtual BTUser Recipient { get; set; }
        
        public virtual BTUser Sender { get; set; }
    }
}

Models/ViewModels/InviteViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace JamesonBugTracker.Models.ViewModels
{
    public class InviteViewModel
    {

        [Display(Name = "Company")]
        public Company Company { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required]
        [Display(Name = "Project")]
        public int ProjectId { get; set; }

        public SelectList ProjectsList { get; set; }

        public string Message { get; set; }
    }

}

Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JamesonBugTracker.Data;
using JamesonBugTracker.Models;
using JamesonBugTracker.Services.Interfaces;
using JamesonBugTracker.Models.ViewModels;
using JamesonBugTracker.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Authorization;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;

namespace JamesonBugTracker.Controllers
{
    [Authorize]
    public class ProjectsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IBTProjectService _projectService;
        private readonly UserManager<BTUser> _userManager;
        private readonly IBTCompanyInfoService _companyInfoService;
        private readonly IBTTicketService _ticketService;
        private readonly IBTFileService _fileService;
        private readonly IConfiguration _configuration;
        private readonly IBTNotificationService _notificationService;


        public ProjectsController(ApplicationDbContext context, IBTProjectService projectService, UserManager<BTUser> userManager, IBTCompanyInfoService companyInfoService, IBTTicketService ticketService, IBTFileService fileService, IConfiguration configuration, IBTNotificationService notificationService)
        {
            _context = context;
            _projectService = projectService;
            _userManager = userManager;
            _companyInfoService = companyInfoService;
            _ticketService = ticketService;
            _fileService = fileService;
            _configuration = configuration;
            _notificationService = notificationService;
        }

        // GET: Projects
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Project.Include(p => p.Company)
                                                       .Include(p => p.ProjectPriority)
                                                       .Include(p => p.Members);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Projects
        public async Task<IActionResult> AllProjects()
        {
            int companyId = User.Identity.GetCompanyId().Value;
            var companyProjects = await _projectService.GetAllUnarchivedProjectsByCompanyAsync(companyId);
            return View(companyProjects);
        }
        public async Task<IActionResult> ArchivedProjects()
        {
            int companyId = User.Identity.GetCompanyId().Value;
            var companyProjects = await _projectService.GetArchivedProjectsByCompanyAsync(companyId);
            return View(companyProjects);
        }

        // GET: Projects
        public async Task<IActionResult> MyProjects()
        {
            var userId = _userManager.GetUserId(User);
            var userProjects = await _projectService.ListUserUnarchivedProjectsAsync(userId);
            return View(userProjects);
        }

        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Project
                .Include(p => p.Tickets)
                .ThenInclude(t => t.TicketPriority)
                .Include(p => p.Tickets)
                .ThenInclude(t => t.TicketStatus)
                .Include(p => p.Tickets)
                .ThenInclude(t => t.TicketType)
                .Include(p => p.Members)
                .Include(p => p.Company)
                .Include(p => p.ProjectPriority)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (project == null)
            {
                return NotFound();
            }
            ProjectDetailsViewModel viewModel = new()
            {
                Project = project,
                OpenTickets = await _ticketService.GetProjectTicketsNotResolvedOrArchivedAsync(project.CompanyId, project.Id),
                ResolvedTickets = await _ticketService.GetProjectTicketsByStatusAsync("Resolved", project.CompanyId, project.Id),
                ArchivedTickets = await _ticketService.GetProjectTicketsByStatusAsync("Archived", project.CompanyId, project.Id)
            };
            return View(viewModel);
        }

        // GET: Projects/Create
        [Authorize(Roles = "Admin,ProjectManager")]

        public IActionResult Create()
        {

            ViewData["ProjectPriorityId"] = new SelectList(_context.Set<ProjectPriority>().OrderBy(t => t.Id), "Id", "Name");
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,ProjectManager")]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,StartDate,EndDate,ProjectPriorityId")] Project project, IFormFile customFile)
        {
            if (ModelState.IsValid)
            {
                project.CompanyId = User.Identity.GetCompanyId().Value;
                if (customFile is not null)
                {
                    project.ImageFileData = await _fileService.ConvertFileToByteArrayAsync(customFile);
                    project.ImageFileContentType = customFile.ContentType;
                }
                else
                {
                    project.ImageFileData = await _fileService.EncodeFileAsync(_configuration["DefaultProjectImage"]);
                    project.ImageFileContentType = _configuration["DefaultProjectImage"].Split('.')[1];
                }
                _context.Add(project);
                await _context.SaveChangesAsync();
                return RedirectToAction("AddMembers", new { id = project.Id });
            }
            ViewData["ProjectPriorityId"] = new SelectList(_context.Set<ProjectPriority>().OrderBy(t => t.Id), "Id", "Id", project.ProjectPriorityId);
            return View(project);
        }

        // GET: Projects/Edit/5
        [Authorize(Roles = "Admin,ProjectManager")]

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Project.FindAsync(id);
            if (project == null)
            {
                return NotFound();
            }
            ViewData["ProjectPriorityId"] = new SelectList(_context.Set<ProjectPriority>().OrderBy(t => t.Id), "Id", "Name", project.ProjectPriorityId);
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,ProjectManager")]

        public async Task<IActionResult> Edit(int id, [Bind("Id,CompanyId,Name,Description,StartDate,EndDate,ArchiveDate,Archived,ImageFileName,ImageFileData,ImageFileContentType,ProjectPriorityId")] Project project, IFormFile customFile)
        {
            if (id != project.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (customFile is not null)
                    {
                        using var image = Image.Load(customFile.OpenReadStream());
                        image.Mutate(x => x.Resize(256, 256));
                        project.ImageFileData = await _fileService.ConvertFileToByteArrayAsync(image, customFile.ContentType);
                        project.ImageFileContentType = customFile.ContentType;
                    }
                    else if (project.ImageFileData is null)
                    {
                        project.ImageFileData = await _fileService.EncodeFileAsync(_configuration["DefaultProjectImage"]);
                        project.ImageFileContentType = _configuration["DefaultProjectImage"].Split('.')[1];
                    }
                    _context.Update(project);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(project.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("MyProjects");
            }
            ViewData["ProjectPriorityId"] = new SelectList(_context.Set<ProjectPriority>().OrderBy(t => t.Id), "Id", "Id", project.ProjectPriorityId);
            return View(project);
        }

        [Authorize(Roles = "Admin,ProjectManager")]
        [HttpGet]
        public async Task<IActionResult> AddMembers(int id)
        {
            //We extended Identity 
            int companyId = User.Identity.GetCompanyId().Value;
            ProjectMembersViewModel model = new();
            var project = (await _projectService.GetAllProjectsByCompanyAsync(companyId))
                                               .FirstOrDefault(p => p.Id == id);
            if (User.IsInRole("ProjectManager") && (await _projectService.GetProjectManagerAsync(id)).Id != _userManager.GetUserId(User))
            {
                TempData["StatusMessage"] = "Error: You are not the project manager for this project";

Controllers/UserRolesController.cs
using JamesonBugTracker.Data;
using JamesonBugTracker.Extensions;
using JamesonBugTracker.Models;
using JamesonBugTracker.Models.Enums;
using JamesonBugTracker.Models.ViewModels;
using JamesonBugTracker.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JamesonBugTracker.Controllers
{
    [Authorize(Roles="Admin")]
    public class UserRolesController : Controller
    {
        private readonly IBTRolesService _rolesService;
        private readonly IBTCompanyInfoService _companyInfoService;
        private readonly UserManager<BTUser> _userManager;
        private readonly ApplicationDbContext _context;

        public UserRolesController(ApplicationDbContext context, UserManager<BTUser> userManager, IBTRolesService bTRolesService, IBTCompanyInfoService companyInfoService)
        {
            _userManager = userManager;
            _rolesService = bTRolesService;
            _context = context;
            _companyInfoService = companyInfoService;
        }
        [Authorize(Roles="Admin")]
        [HttpGet]
        public async Task<IActionResult> ManageUserRoles()
        {
            if (User.IsInRole("DemoUser"))
            {
                return RedirectToAction("DemoError", "Home");
            }
            List<ManageUserRolesViewModel> model = new();
            int companyId = User.Identity.GetCompanyId().Value;
            List<BTUser> users = await _companyInfoService.GetAllMembersAsync(companyId);
            foreach (var user in users)
            {
                ManageUserRolesViewModel vm = new();
                vm.BTUser = user;
                var selected = await _rolesService.ListUserRolesAsync(user);
                vm.Roles = new MultiSelectList(_context.Roles, "Name", "Name", selected);
                model.Add(vm);
            }
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ManageUserRoles(ManageUserRolesViewModel member)
        {
            if (User.IsInRole("DemoUser"))
            {
                return RedirectToAction("DemoError", "Home");
            }
            BTUser user = _context.Users.Find(member.BTUser.Id);
            IEnumerable<string> roles = await _rolesService.ListUserRolesAsync(user);
            await _rolesService.RemoveUserFromRolesAsync(user, roles); // TODO refactor
            string userRole = member.SelectedRoles.FirstOrDefault();

            if (Enum.TryParse(userRole, out Roles roleValue))
            {
                await _rolesService.AddUserToRoleAsync(user, userRole);
                return RedirectToAction("ManageUserRoles");

            }
            return RedirectToAction("ManageUserRoles");
        }
    }
}

Views/Invites/Create.cshtml
@model JamesonBugTracker.Models.ViewModels.InviteViewModel

<h1>Create</h1>
<div class="row">
    <div class="col-md-12">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">New Invite</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                </div>
            </div>
            <div class="card-body">
                <p>User will receive an invite, giving them a link to register.  Once registered, they will automatically be assigned to the selected project and given the role of "submitter".</p>
                <p>To change user's role, visit the <a asp-controller="UserRoles" asp-action="ManageUserRoles">Manage User Roles</a> page. </p>
                <p>To add an existing user to another project, visit the <a asp-controller="Projects" asp-action="All Projects" >Project Index</a> and click assign users.  <span class="text-muted">(A project manager can also do this for projects they manage)</span></p>
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input type="email" asp-for="Email" class="form-control" placeholder="Enter email">
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FirstName" class="control-label"></label>
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LastName" class="control-label"></label>
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ProjectId" class="control-label"></label>
                        <select asp-for="ProjectId" class="form-control" asp-items="Model.ProjectsList">
                            <option hidden>Select a project</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <input type="submit" class="btn ripple btn-primary pd-x-30 mg-r-5" value="Send Invite" />
                        <button class="btn ripple btn-secondary pd-x-30">Cancel</button>

                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Views/Invites/Details.cshtml
@model JamesonBugTracker.Models.Invite

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Invite</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InviteDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InviteDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyToken)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompanyToken)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RecipientEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RecipientEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsValid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsValid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Company.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Project)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Project.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Recipient)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Recipient.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sender.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Invites/ProcessInvite.cshtml
@model JamesonBugTracker.Models.Invite

@{ Layout = "_LoginLayout";
                ViewData["Title"] = "Register"; }

<div id="wrapper">
    <div class="vertical-align-wrap">
        <div class="vertical-align-middle auth-main">
            <div class="auth-box">
                <div class="top">
                </div>
                <div class="card">
                    <div class="header">
                        <h3>
                            <span class="clearfix title">
                                <span class="number">Welcome</span><br />
                                <span>@Model.FirstName @Model.LastName!</span> <br>
                            </span>
                        </h3>
                        <h5><span>@Model.Company.Name Company</span></h5>
                    </div>

                    <div class="body">
                        <p>
                            @Model.Sender.FullName has invited you to collaborate on the @Model.Project.Name project.
                            <br /><br /> Click the "JOIN" button below to register with the company and begin entering tickets.
                        </p>
                        <a class="btn btn-primary btn-lg btn-block" asp-area="Identity" asp-page="/Account/RegisterByInvite" asp-route-id="@Model.Id"><i class="fa fa-sign-in"></i> <span>JOIN</span></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}